name: Build
on: 
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@master
    - name: Install Python packages
      run: pip3 install ninja
    - name: Install Python 2 packages
      run: pip2 install intelhex
    - name: Setup ninja-build
      uses: seanmiddleditch/gha-setup-ninja@master
    - name: Setup ARM GNU tools
      run: sudo apt install gcc-arm-none-eabi
    - name: Build
      run: cd Firmware && ninja
#    - name: Upload coverage report
#      uses: actions/upload-artifact@v1
#      with:
#        name: coverage_report
#        path: Firmware/unit_tests/coverage_report
