name: unit-tests
on: 
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: textbook/git-checkout-submodule-action@master
    - name: Install Python packages
      run: pip3 install ninja
    - name: Setup ninja-build
      uses: seanmiddleditch/gha-setup-ninja@master
    - name: Setup gtest
      run: .github/workflows/setup_gtest
    - name: Run
      run: Firmware/unit_tests/run -c

